#! /usr/bin/env python

import argparse
import shutil
import subprocess
import sys
import os

from oclintscripts import environment
from oclintscripts import path

OCLINT_MODULES = ['core', 'metrics', 'rules', 'reporters', 'driver']

arg_parser = argparse.ArgumentParser()
arg_parser.add_argument('module_name', nargs='?', choices=['all'] + OCLINT_MODULES, default='all')
arg_parser.add_argument('-enable-clang-static-analyzer', '--enable-clang-static-analyzer', action="store_true")
arg_parser.add_argument('-show', '--show', action="store_true")
args = arg_parser.parse_args()

def clean_module(module_name):
    champagne_path = path.oclint_module_champagne_dir(module_name)
    if os.path.isdir(champagne_path):
        shutil.rmtree(champagne_path)

def build_command(module_extras, source_path):
    command = 'cmake'
    if environment.is_mingw32():
        command += ' -G "MSYS Makefiles"'
    command += ' -D CMAKE_EXPORT_COMPILE_COMMANDS=ON'
    if environment.is_unix():
        clang_bin_path = os.path.join(path.build.clang_install_dir, 'bin', 'clang')
        command += ' -D CMAKE_CXX_COMPILER=' + clang_bin_path + '++ -D CMAKE_C_COMPILER=' + clang_bin_path
    extras = {'LLVM_ROOT': path.build.clang_install_dir}
    extras.update(module_extras)
    for extra_key, extra_value in extras.items():
        command += ' -D ' + extra_key + '='
        if environment.is_mingw32():
            command += '"'
        command += extra_value
        if environment.is_mingw32():
            command += '"'
    command += ' '
    if environment.is_mingw32():
        command += '"'
    command += source_path
    if environment.is_mingw32():
        command += '"'
    return command

def build_module(module_name):
    build_path = path.oclint_module_champagne_dir(module_name)
    source_path = path.oclint_module_source_dir(module_name)

    module_extras = {}
    if module_name == "rules" or module_name == "reporters" or module_name == "driver":
        module_extras['OCLINT_SOURCE_DIR'] = path.source.core_dir
        module_extras['OCLINT_BUILD_DIR'] = path.build.core_build_dir
    if module_name == "rules":
        module_extras['OCLINT_METRICS_SOURCE_DIR'] = path.source.metrics_dir
        module_extras['OCLINT_METRICS_BUILD_DIR'] = path.build.metrics_build_dir

    command = build_command(module_extras, source_path)
    print command

    current_dir = os.getcwd()
    if not os.path.isdir(build_path):
        os.mkdir(build_path)
    os.chdir(build_path)
    cmake_exit_code = subprocess.call(command, shell=True)
    if cmake_exit_code:
        sys.exit(cmake_exit_code)
    os.chdir(current_dir)

    compile_commands_file_name = 'compile_commands.json'
    compile_commands_src_path = os.path.join(build_path, compile_commands_file_name)
    compile_commands_dst_path = os.path.join(source_path, compile_commands_file_name)
    shutil.copy2(compile_commands_src_path, compile_commands_dst_path)

def result_path(module_name):
    build_path = path.oclint_module_champagne_dir(module_name)
    return os.path.join(build_path, 'champagne_results.txt')

def display_result(module_name):
    with open(result_path(module_name), 'r') as result_file:
        print result_file.read()

def drink_champagne(module_name, enable_clang_static_analyzer):
    source_path = path.oclint_module_source_dir(module_name)
    oclint_json_compilation_database_path = os.path.join(path.build.bundle_dir, 'bin', 'oclint-json-compilation-database')
    command = oclint_json_compilation_database_path + ' -- -debug'
    if enable_clang_static_analyzer:
        command += ' -enable-clang-static-analyzer'
    command += ' -o ' + result_path(module_name)

    current_dir = os.getcwd()
    os.chdir(source_path)
    champagne_exit_code = subprocess.call(command, shell=True)
    if champagne_exit_code:
        sys.exit(champagne_exit_code)
    os.chdir(current_dir)

build_modules = []
if args.module_name == 'all':
    build_modules.extend(OCLINT_MODULES)
else:
    build_modules.append(args.module_name)

if args.show:
    for module in build_modules:
        display_result(module)
    sys.exit(0)

for module in build_modules:
    clean_module(module)
    build_module(module)
    drink_champagne(module, args.enable_clang_static_analyzer)
    display_result(module)
