#! /bin/sh -e

./build core -docgen -no-ninja
./build metrics -docgen -no-ninja
./build rules -docgen -no-ninja
./build driver -docgen -no-ninja
./bundle -docgen
mkdir -p ../build/oclint-docs/rules
../build/oclint-release/bin/oclint-docgen docgen
cd ../build/
tar zcf oclint-docs-dev-snapshot.tar.gz oclint-docs/
