#! /bin/sh -e

./build core -docgen
./build metrics -docgen
./build rules -docgen
./build driver -docgen
./bundle -docgen
mkdir -p ../build/oclint-docs/rules
../build/oclint-release/bin/oclint-docgen docgen
cd ../build/
tar zcf oclint-docs-dev-snapshot.tar.gz oclint-docs/
