#! /bin/sh -e

./clang prebuilt
if [ "$1" = "build" ]
then
    ./build
    ./bundle -archive
elif [ "$1" == "docgen" ]
then
    ./docGen
else
    ./googleTest co
    ./googleTest build
    shift
    MODULE="$1"
    shift
    for dep in $*
    do
        ./test "$dep" -as-dep
    done
    ./test "$MODULE"
fi
