#! /bin/sh -e

./clang prebuilt
if [ "$1" = "build" ]
then
    ./build
    ./bundle -archive
else
    ./googleTest co
    ./googleTest build
    shift
    MODULE="$1"
    shift
    for dep in $*
    do
        ./build "$dep"
    done
    ./test "$MODULE"
fi
